### ISSUE TITLE
Can't reproduce the code from readme

### ISSUE THREAD

**Issue by Shmublon** [Only-IceSoul/react-native-blurview#1]
Hi, it looks like something I'm really looking for! But unfortunatelly I can't reproduce the picture in readme using code in readme, can you make an example code? It will be really helpfull.

**Comment by Only-IceSoul** [comment]
https://m.youtube.com/watch?v=CIpZ_3ve-OY

https://github.com/Only-IceSoul/canal/tree/master/react-native/Car%20Insurance%20Claim

**Comment by Only-IceSoul** [comment]
Readme updated!
